[package]
name = "rust-cpu-info"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.16.0"
sys-info = "0.9.0"
termion = "1.5"

